/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as SearchSearchIdRouteImport } from './routes/search.$searchId'
import { Route as ApiJobJobIdRouteImport } from './routes/api/job/$jobId'
import { Route as ApiSearchSearchIdRouteImport } from './routes/api/search.$searchId'
import { Route as ApiJobJobIdCrmRouteImport } from './routes/api/job/$jobId.crm'
import { Route as ApiJobJobIdScoreRouteImport } from './routes/api/job/$jobId.score'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchSearchIdRoute = SearchSearchIdRouteImport.update({
  id: '/search/$searchId',
  path: '/search/$searchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobJobIdRoute = ApiJobJobIdRouteImport.update({
  id: '/api/job/$jobId',
  path: '/api/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchSearchIdRoute = ApiSearchSearchIdRouteImport.update({
  id: '/$searchId',
  path: '/$searchId',
  getParentRoute: () => ApiSearchRoute,
} as any)
const ApiJobJobIdCrmRoute = ApiJobJobIdCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => ApiJobJobIdRoute,
} as any)
const ApiJobJobIdScoreRoute = ApiJobJobIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => ApiJobJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/search/$searchId': typeof SearchSearchIdRoute
  '/api/job/$jobId': typeof ApiJobJobIdRouteWithChildren
  '/api/search/$searchId': typeof ApiSearchSearchIdRoute
  '/api/job/$jobId/crm': typeof ApiJobJobIdCrmRoute
  '/api/job/$jobId/score': typeof ApiJobJobIdScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/search/$searchId': typeof SearchSearchIdRoute
  '/api/job/$jobId': typeof ApiJobJobIdRouteWithChildren
  '/api/search/$searchId': typeof ApiSearchSearchIdRoute
  '/api/job/$jobId/crm': typeof ApiJobJobIdCrmRoute
  '/api/job/$jobId/score': typeof ApiJobJobIdScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/search/$searchId': typeof SearchSearchIdRoute
  '/api/job/$jobId': typeof ApiJobJobIdRouteWithChildren
  '/api/search/$searchId': typeof ApiSearchSearchIdRoute
  '/api/job/$jobId/crm': typeof ApiJobJobIdCrmRoute
  '/api/job/$jobId/score': typeof ApiJobJobIdScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/api/export'
    | '/api/history'
    | '/api/search'
    | '/search/$searchId'
    | '/api/job/$jobId'
    | '/api/search/$searchId'
    | '/api/job/$jobId/crm'
    | '/api/job/$jobId/score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/api/export'
    | '/api/history'
    | '/api/search'
    | '/search/$searchId'
    | '/api/job/$jobId'
    | '/api/search/$searchId'
    | '/api/job/$jobId/crm'
    | '/api/job/$jobId/score'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/api/export'
    | '/api/history'
    | '/api/search'
    | '/search/$searchId'
    | '/api/job/$jobId'
    | '/api/search/$searchId'
    | '/api/job/$jobId/crm'
    | '/api/job/$jobId/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiSearchRoute: typeof ApiSearchRouteWithChildren
  SearchSearchIdRoute: typeof SearchSearchIdRoute
  ApiJobJobIdRoute: typeof ApiJobJobIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$searchId': {
      id: '/search/$searchId'
      path: '/search/$searchId'
      fullPath: '/search/$searchId'
      preLoaderRoute: typeof SearchSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job/$jobId': {
      id: '/api/job/$jobId'
      path: '/api/job/$jobId'
      fullPath: '/api/job/$jobId'
      preLoaderRoute: typeof ApiJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/$searchId': {
      id: '/api/search/$searchId'
      path: '/$searchId'
      fullPath: '/api/search/$searchId'
      preLoaderRoute: typeof ApiSearchSearchIdRouteImport
      parentRoute: typeof ApiSearchRoute
    }
    '/api/job/$jobId/crm': {
      id: '/api/job/$jobId/crm'
      path: '/crm'
      fullPath: '/api/job/$jobId/crm'
      preLoaderRoute: typeof ApiJobJobIdCrmRouteImport
      parentRoute: typeof ApiJobJobIdRoute
    }
    '/api/job/$jobId/score': {
      id: '/api/job/$jobId/score'
      path: '/score'
      fullPath: '/api/job/$jobId/score'
      preLoaderRoute: typeof ApiJobJobIdScoreRouteImport
      parentRoute: typeof ApiJobJobIdRoute
    }
  }
}

interface ApiSearchRouteChildren {
  ApiSearchSearchIdRoute: typeof ApiSearchSearchIdRoute
}

const ApiSearchRouteChildren: ApiSearchRouteChildren = {
  ApiSearchSearchIdRoute: ApiSearchSearchIdRoute,
}

const ApiSearchRouteWithChildren = ApiSearchRoute._addFileChildren(
  ApiSearchRouteChildren,
)

interface ApiJobJobIdRouteChildren {
  ApiJobJobIdCrmRoute: typeof ApiJobJobIdCrmRoute
  ApiJobJobIdScoreRoute: typeof ApiJobJobIdScoreRoute
}

const ApiJobJobIdRouteChildren: ApiJobJobIdRouteChildren = {
  ApiJobJobIdCrmRoute: ApiJobJobIdCrmRoute,
  ApiJobJobIdScoreRoute: ApiJobJobIdScoreRoute,
}

const ApiJobJobIdRouteWithChildren = ApiJobJobIdRoute._addFileChildren(
  ApiJobJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ApiExportRoute: ApiExportRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiSearchRoute: ApiSearchRouteWithChildren,
  SearchSearchIdRoute: SearchSearchIdRoute,
  ApiJobJobIdRoute: ApiJobJobIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
