/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSearchSearchIdRouteImport } from './routes/api/search.$searchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchSearchIdRoute = ApiSearchSearchIdRouteImport.update({
  id: '/$searchId',
  path: '/$searchId',
  getParentRoute: () => ApiSearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/search/$searchId': typeof ApiSearchSearchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/search/$searchId': typeof ApiSearchSearchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/search/$searchId': typeof ApiSearchSearchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/export'
    | '/api/history'
    | '/api/search'
    | '/api/search/$searchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/export'
    | '/api/history'
    | '/api/search'
    | '/api/search/$searchId'
  id:
    | '__root__'
    | '/'
    | '/api/export'
    | '/api/history'
    | '/api/search'
    | '/api/search/$searchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiSearchRoute: typeof ApiSearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/$searchId': {
      id: '/api/search/$searchId'
      path: '/$searchId'
      fullPath: '/api/search/$searchId'
      preLoaderRoute: typeof ApiSearchSearchIdRouteImport
      parentRoute: typeof ApiSearchRoute
    }
  }
}

interface ApiSearchRouteChildren {
  ApiSearchSearchIdRoute: typeof ApiSearchSearchIdRoute
}

const ApiSearchRouteChildren: ApiSearchRouteChildren = {
  ApiSearchSearchIdRoute: ApiSearchSearchIdRoute,
}

const ApiSearchRouteWithChildren = ApiSearchRoute._addFileChildren(
  ApiSearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExportRoute: ApiExportRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiSearchRoute: ApiSearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
